[ISSUE #2686] ConsulSyncDataServiceTest.testWatch AssertionError: expected:<1> but was:<0>
Fixes #2686
fixed bug and remove reflection code. the private method does not require testing .