[type:feat] upgrade dockerfile java runtime version 8 to 17 (#5374)
* upgrade dockerfile java runtime version 8 to 17

* update jdk runtime version

* update jdk runtime version 17

* update jdk runtime version 17

* cannot find symbol Error:class Resource

* update jdk runtime version 17

* update jdk runtime version 17

* update jdk runtime version 17

* fix Unrecognized VM option 'UseFastAccessorMethods'

* Add test case for `AbstractWasmDiscoveryHandler` (#5453)

* Tests

* Updated lib.rs and added a README.md

I updated the `lib.rs` and updated the WASM file and also added a README.md

* Remove TestWasmPluginDiscoveryHandler#handlerDiscoveryUpstreamData

* Revert "Remove TestWasmPluginDiscoveryHandler#handlerDiscoveryUpstreamData"

This reverts commit c85d3dbbe9c43159236f8e073cb0a9320e6d0a01.

* Update AbstractWasmDiscoveryHandlerTest.java

---------

Co-authored-by: loongs-zhang <zhangzicheng@apache.org>

* fix AbstractWasmPluginDataHandlerTest (#5464)

* fix AbstractWasmPluginDataHandlerTest

* [ISSUE #5427] add AbstractWasmMetaDataHandlerTest

* fix spring-boot-starter-client-springmvc: fix expired comments. (#5463)

Co-authored-by: likeguo <33576070+li-keguo@users.noreply.github.com>

* [BUG] websocket offline don't remove upstream in database #5460 (#5462)

* add offline in grpc and websocket

* trigger ci

* trigger ci

---------

Co-authored-by: xiaoyu <xiaoyu@apache.org>
Co-authored-by: loongs-zhang <zhangzicheng@apache.org>

* refactor shenyu-sync-data-http : replace log %s -> {}. (#5465)

Co-authored-by: moremind <hefengen@apache.org>

* Encrypt the password (#5436)

* Encrypt the password

* Encrypt the password

* add client meta-information registration login

* Modified to AES/CTR/NoPadding mode

* Adding Exception Handling to Avoid NPE

* add doc

* Update key acquisition method

* Update key acquisition method and format

* Modified to AES/CBC/Pkcs7Padding mode

* delete blank

---------

Co-authored-by: 2252603132 <85060647+2252603132@users.noreply.github.com>
Co-authored-by: loongs-zhang <zhangzicheng@apache.org>
Co-authored-by: likeguo <33576070+li-keguo@users.noreply.github.com>
Co-authored-by: wln <w2252603132@gmail.com>

* [type: refactor] Admin distributed lock by spring-integration-jdbc (#5457)

* [type: refactor] Admin distributed lock by spring-integration-jdbc

* fix ci

* supplementary testing

* add a table for all SQL

* lock operation put it in try statement block

* fix-ci mock ReentrantLock cpu 100%

---------

Co-authored-by: moremind <hefengen@apache.org>

* [BUG] update app_key in db (#5471)

* AbstractNodeDataSyncService load discoverUpstream on startup (#5472) (#5473)

* [type:feature] enhance metrics-ratelimiter collect (#5461)

* [type:refactor] enhance metrics-ratelimiter collect

* [type:refactor] enhance metrics-ratelimiter collect

---------

Co-authored-by: xiaoyu <xiaoyu@apache.org>
Co-authored-by: loongs-zhang <zhangzicheng@apache.org>

* fixed #5477 (#5478)

* update image due wget not found

* update

* update

* update

* update

* update

* use 8 build

* use 8 build

* Revert "update"

This reverts commit d67da20d8c7fa669e9d4913742dbb7029b1da441.

* use 8 build

* update

* update

* update

* Revert "update"

This reverts commit bc1cc49cea1a7f67eca7fed73b00cd3150b68349.

* modify base image

* jdk17 support: modify base image

* jdk17 support: add null check

* jdk17 support: timestamp type adapter

* jdk17 support: gson modify

* jdk17 support: gson modify

* jdk17 support: gson modify

* jdk17 support: gson timestamp

* jdk17 support: gson timestamp

* jdk17 support: ci debug

* jdk17 support: ci debug mysql test

* jdk17 support: ci debug mysql test

* jdk17 support: ci debug mysql test

* jdk17 support: ci debug

* jdk17 support: ci debug mysql test

* jdk17 support: modify base image

* jdk17 support: ci debug

* jdk17 support: modify base image

* jdk17 support: modify jdbc env key

* jdk17 support: h2 sync

* jdk17 support: bootstrap base image

* jdk17 support: change base image

* jdk17 support: admin base image\e2e env config

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: ci build use jdk 17

* jdk17 support: ci build use jdk 17

* jdk17 support: ci build use jdk 17

* jdk17 support: ci build use jdk 17

* jdk17 support: ci build use jdk 17

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: base image

* jdk17 support: sofa base image

* jdk17 support: sofa base image

* jdk17 support: sofa base image

* jdk17 support: dubbo base image

* jdk17 support: e2e mysql

* jdk17 support: e2e h2

* jdk17 support: e2e mysql

* jdk17 support: eureka jdk 17

* jdk17 support: dubbo jdk 17

* jdk17 support: e2e timeout

* jdk17 support: combination

* jdk17 support: combination

* jdk17 support: combination

* jdk17 support: e2e timeout

* jdk17 support: change base jdk image

* jdk17 support: motan image

* jdk17 support: debug

* jdk17 support: motan image

* jdk17 support: base image

* jdk17 support: motan example base image

* jdk17 support: motan jdk17

* jdk17 support: motan jdk17

* jdk17 support: ci debug

* jdk17 support: ci debug

* jdk17 support: change base image based on alpine

* jdk17 support: change base image based on alpine

* jdk17 support: change base image based on alpine

* jdk17 support: change base image to amazoncorretto:17.0.11-alpine3.19

---------

Co-authored-by: yunlongn <yunlongn@outlook.com>
Co-authored-by: dragon-zhang <zhangzicheng@apache.org>
Co-authored-by: Divyansh200102 <146909065+Divyansh200102@users.noreply.github.com>
Co-authored-by: caaaaaat <875411010@qq.com>
Co-authored-by: likeguo <33576070+li-keguo@users.noreply.github.com>
Co-authored-by: 杨文杰 <31105009+ywj1352@users.noreply.github.com>
Co-authored-by: xiaoyu <xiaoyu@apache.org>
Co-authored-by: frank <shaoshuai_yy@163.com>
Co-authored-by: moremind <hefengen@apache.org>
Co-authored-by: wlngo <85060647+wlngo@users.noreply.github.com>
Co-authored-by: 2252603132 <85060647+2252603132@users.noreply.github.com>
Co-authored-by: wln <w2252603132@gmail.com>
Co-authored-by: crudboy <965211455@qq.com>
Co-authored-by: dyjxg4xygary <1140408986@qq.com>
Co-authored-by: Kerwin Bryant <kerwin612@qq.com>
Co-authored-by: liuhy <rokkki@163.com>