Issues 1065 fix:Remove dependency of commons-dbcp from soul-admin to fix NoClassDefFoundError, which caused by same package 'org.w3c.dom' conflict of transitive dependency 'xercesImpl' and module 'jdk.xml.dom' of JDK11. (#1066)